name: vetconnect
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_fonts: ^6.1.0
  provider: ^6.1.1
  intl: ^0.17.0
  image_picker: ^1.0.5
  firebase_storage: ^11.5.6
  cached_network_image: ^3.3.0
  flutter_local_notifications: ^16.2.0
  firebase_messaging: ^14.7.9
  url_launcher: ^6.2.2
  font_awesome_flutter: ^10.6.0
  material_design_icons_flutter: ^7.0.7296
  shared_preferences: ^2.5.2
  js: ^0.6.7
  datetime_picker_formfield_new: ^2.1.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_dotenv: ^5.2.1
  mpesa_flutter_plugin: ^1.6.1
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    
  fonts:
    - family: RobotoSerif
      fonts:
        - asset: assets/fonts/RobotoSerif-VariableFont_GRAD,opsz,wdth,wght.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

