// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDGBu-6R_feaBsJ4ZEqZlgVnMML7oq3DY',
    appId: '1:973000814272:web:19b2c17913680fef118725',
    messagingSenderId: '973000814272',
    projectId: 'vetconnect-d20f8',
    authDomain: 'vetconnect-d20f8.firebaseapp.com',
    storageBucket: 'vetconnect-d20f8.firebasestorage.app',
    measurementId: 'G-FQT9HVLMV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUS0XpaY13HdXqAw6m5Hpt4-lhwKPY_ac',
    appId: '1:973000814272:android:ae136dd9f71a865e118725',
    messagingSenderId: '973000814272',
    projectId: 'vetconnect-d20f8',
    storageBucket: 'vetconnect-d20f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKgkBMvvwfIbcDkQBj946Az_Qfg5kXKaw',
    appId: '1:973000814272:ios:694b8f56cb6c395d118725',
    messagingSenderId: '973000814272',
    projectId: 'vetconnect-d20f8',
    storageBucket: 'vetconnect-d20f8.firebasestorage.app',
    iosBundleId: 'com.example.vetconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKgkBMvvwfIbcDkQBj946Az_Qfg5kXKaw',
    appId: '1:973000814272:ios:694b8f56cb6c395d118725',
    messagingSenderId: '973000814272',
    projectId: 'vetconnect-d20f8',
    storageBucket: 'vetconnect-d20f8.firebasestorage.app',
    iosBundleId: 'com.example.vetconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDGBu-6R_feaBsJ4ZEqZlgVnMML7oq3DY',
    appId: '1:973000814272:web:1f467640fc1fe03a118725',
    messagingSenderId: '973000814272',
    projectId: 'vetconnect-d20f8',
    authDomain: 'vetconnect-d20f8.firebaseapp.com',
    storageBucket: 'vetconnect-d20f8.firebasestorage.app',
    measurementId: 'G-2KSK4TB09V',
  );
}
